#!/bin/zsh
set -eux -o pipefail

# switch to HWE for ubuntu 20.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
#sudo apt-get update
#sudo apt-get upgrade -qqy
# todo hwe-20.04 not there (yet)
#sudo apt-get install -qqy --install-recommends xserver-xorg-hwe-20.04
echo 'note: xserver-xorg-hwe-20.04 might be ready now, did not exist on 2021-11-05'

sudo apt-get install -yqq xinit # for startx

# using the right target should prevent any greeter from appearing?
# not sure, so currently I still explicitely disable gdm as well
sudo systemctl disable gdm.service
sudo systemctl stop gdm.service
sudo systemctl set-default multi-user.target

${0:a:h}/../nvidia/setup
echo 'nvidia-smi wont work before restart'

# apt installs (sorted)
i=()
i+=evince
i+=feh
i+=firefox
i+=geeqie
i+=gnome-sushi
i+=gthumb
i+=nautilus
i+=scrot
i+=suckless-tools
i+=fonts-ubuntu
i+=usbmount
i+=xclip
i+=xdotool
i+=vlc
sudo apt-get install -qqy $i

# ordered list of custom setups
setups=(
    alacritty
    chrome
    docker
    dwm
    ltstatus
    off-blast
    redshift
    roam
    slack
    sound
    spotify
    steam
    syncthing
)
for i in $setups; do
    ${0:a:h}/../$i/setup
done

# todo maybe some of the above need to be added as interactive? or just on demand? not all are fully unattended
