#!/bin/zsh
set -eux -o pipefail

sudo apt-get -q install -y openssh-server

# server configuration is at
#   /etc/ssh/sshd_config
# and
#   /etc/ssh/sshd_config.d/* (takes precedence)

# disable password login
echo 'PasswordAuthentication no' | sudo tee /etc/ssh/sshd_config.d/disable-password
echo 'maybe that will disconnect ssh'
sudo systemctl restart ssh sshd  # seems like ssh is actually the server?

mkdir -p ~/.ssh

# TODO ssh config?
