#!/bin/bash
set -eux -o pipefail

# bash <(curl https://raw.githubusercontent.com/iff/dotfiles/master/bootstrap/sh)

install_gh() {
    sudo apt install gpg
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt update
    sudo apt install gh
}

which gh || install_gh

# create a key per machine
mkdir -p ~/.ssh
hostname=$(cat /proc/sys/kernel/hostname)
ssh-keygen -t ed25519 -C "iff@yvesineichen.com" -f ~/.ssh/${hostname} -N ''

gh auth login --hostname GitHub.com

echo "IdentityFile ~/.ssh/${hostname}" >> ~/.ssh/config
git clone git@github.com:iff/dotfiles.git ~/.dotfiles --recurse-submodules
