#!/bin/zsh
set -eux -o pipefail

if ! which roam-research; then
    wget \
        'https://roam-electron-deploy.s3.us-east-2.amazonaws.com/roam-research_0.0.13_amd64.deb' \
        -O /tmp/roam.deb
    sudo apt-get install -yqq /tmp/roam.deb
    rm /tmp/roam.deb
fi
