#!/bin/zsh
set -eux -o pipefail

# ubuntu 20.04 has a recent version of docker
sudo apt-get -yqq install docker.io

# test
sudo docker run hello-world

# to use it without sudo
sudo usermod -a -G docker $USER
echo 'use of docker without sudo only takes effect after new login, ssh localhost, su --login $USER, new tmux server, ...'
