#!/bin/zsh
set -eux -o pipefail

sudo apt-get install -yq python3.9 build-essential

# NOTE
# even though there can be multiple more pythons installed
# after the below, virtualenv and ipython commands point at this python version install
# I'm not sure, but I think whatever python version pip did it last determines what's available globally
python3.9 -m pip install --upgrade pip virtualenv ipython
