#!/bin/zsh
set -eux -o pipefail

# https://docs.syncthing.net/intro/getting-started.html
# ubuntu repo has a very old version
# snap seems pretty up-to-date versions but doesn't correctly setup a systemd service for me
# now we do from https://apt.syncthing.net/
# (but maybe snap would have worked and I wasn't patient enough)
curl -sS https://syncthing.net/release-key.txt | sudo apt-key add -
echo 'deb https://apt.syncthing.net/ syncthing stable' | sudo tee /etc/apt/sources.list.d/syncthing.list
sudo apt-get update
sudo apt-get install syncthing

# https://docs.syncthing.net/users/autostart.html#linux
# just to be sure
sudo systemctl enable syncthing@$USER.service
sudo systemctl start syncthing@$USER.service
sudo systemctl status syncthing@$USER.service
