#!/bin/zsh

# nodejs and pyright
mkdir -p $HOME/bin/nodejs 
curl -sfLS install-node.vercel.app | bash -s -- --prefix=$HOME/bin/nodejs

path=(
    $HOME/bin/nodejs
    $path
)
export path PATH
npm install -g pyright

# rust
curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/bin/rust-analyzer && chmod +x ~/bin/rust-analyzer

# lua sumneko
# TODO add to path?
mkdir -p ~/bin/sumneko && cd ~/bin/sumneko
curl -L https://github.com/sumneko/lua-language-server/releases/download/3.2.1/lua-language-server-3.2.1-linux-x64.tar.gz | tar xvfz

wget -O /tmp/stylua.zip 'https://github.com/JohnnyMorganz/StyLua/releases/download/v0.14.2/stylua-linux.zip'
cd ~/bin && unzip /tmp/stylua.zip && rm /tmp/stylua.zip
chmod +x ~/bin/stylua
