#!/bin/zsh
set -eux -o pipefail

cd ${0:a:h}/nvim

sudo apt-get install -yqq ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

# maybe to start fresh: make distclean
make CMAKE_BUILD_TYPE=Release
# todo any list of features like in vim?
sudo make install
