#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}

i=()
i+=xinit
i+=xdotool
sudo apt-get install -yqq $i

mkdir -p $HOME/bin

( # grab
    cd $h/off-blast/src/grab
    make install DESTDIR=$HOME/bin
)

( # off-blast
    ln -sfT $h/off-blast/bin/lstcmds $HOME/bin/lstcmds
    ln -sfT $h/off-blast/bin/off-blast $HOME/bin/off-blast
    ln -sfT $h/off-blast/bin/gds $HOME/bin/gds
)
