export MYZSH=$HOME/.dotfiles/

alias src=source
# alias src='source $MYZSH/zsh/timed-source.zsh'

src $MYZSH/zsh/config.zsh
src $MYZSH/zsh/prompt.zsh

# load every completion after autocomplete loads
src $MYZSH/zsh/completion.zsh

path=(
    # FIXME remove and use direnv in projects
    $HOME/bin/nodejs/bin
    $HOME/.cargo/bin
    $path
)

# path -> reverse -> keep only first unique -> reverse
# prevents any duplication for paths that are already setup
path=(${(Oa)${(u)${(Oa)path}}})
export path PATH

# source one-shell-history after setting paths (needs binary in bin)
# only if installed on LINUX
# src $MYZSH/bootstrap/one-shell-history/one-shell-history/shells/zsh
