#!/bin/bash
set -eux -o pipefail

$(dirname $0)/../zsh/setup

# switch to zsh
if [ -z ${ZSH_VERSION+1} ]; then
    exec zsh $0
fi

cd ${0:a:h}

# pip3 needs this, after setup it's in the zsh config
export PATH=$HOME/.local/bin:$PATH

# do this early so we dont get LC_* warnings and slow regeneration
../locales/setup
export LANG=en_US.UTF-8
export LC_ALL=

# switch to HWE for ubuntu 20.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
sudo apt-get update
sudo apt-get upgrade -qqy
sudo apt-get install -qqy --install-recommends linux-generic-hwe-20.04
sudo apt-get autoremove -y

sudo timedatectl set-timezone Europe/Zurich

# apt installs (sorted)
i=()
i+=apt-file # apt-file list [package] to see before you install (instead of manually apt-get download [package]; dpgk --contents [file])
i+=aptitude # 'aptitude why package' is quite cool, there might be more
i+=bmon # bandwidth monitor
i+=cmake
i+=dkms
i+=g++
i+=gcp # like cp, but with progress bar among other features
i+=git
i+=htop
i+=jq # json query engine
i+=lnav # log file viewer
i+=mlocate # quickly find files in the full system
i+=moreutils # sponge
i+=openssh-server
i+=pv # monitor data progress thru a pipe
i+=suckless-tools
i+=sysstat
i+=tree
i+=unzip
i+=zip
sudo apt-get install -qqy $i

# ordered list of custom setups
setups=(
    ssh
    git
    fzf
    python
    pdocs
    ptags
    tmux
    nvim
    nix
)
for i in $setups; do
    ../$i/setup
done

echo 'done'
