name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: blackhole
          - os: ubuntu-latest
            target: nixos
          - os: macos-14
            target: urithiru
    runs-on: ${{ matrix.os }}

    steps:
      - name: nix mount point
        if: contains(matrix.os, 'ubuntu')
        run: sudo mkdir /nix

      - name: maximize space
        uses: easimon/maximize-build-space@v9
        if: contains(matrix.os, 'ubuntu')
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: /nix
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true
          overprovision-lvm: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: cachix
        uses: cachix/cachix-action@v14
        with:
          name: iff-dotfiles
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: build target
        run: |
          set -o pipefail
          nix --accept-flake-config build .#top.${{ matrix.target }} --fallback -v --log-format raw > >(tee /tmp/nix-build-out.log) 2> >(tee /tmp/nix-build-err.log >&2)

      - name: output build failure
        if: failure()
        run: |
          drv=$(grep "For full logs, run" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
          if [ -n $drv ]; then
            nix log $drv
            echo $drv
          fi
          exit 1
