name: NixOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Nix dir"
        run: |
          sudo mkdir /nix
      - name: "Maximize Disk Space"
        uses: easimon/maximize-build-space@v6
        with:
          build-mount-path: /nix
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
      - uses: actions/checkout@v3

      - name: "Install Nix"
        uses: cachix/install-nix-action@v18
        with:
          github_access_token: ${{ secrets.TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check

      - name: "Install Cachix"
        uses: cachix/cachix-action@v10
        with:
          name: ruixi-rebirth
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - name: "Build Nix config"
        run: |
          nix --experimental-features 'nix-command flakes' run . switch -- --flake .#darktower

      - name: "Print nixpkgs version"
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
